#T:\DOcuments\Research2020\99CSVtoSQLForeignKey.ps1  generates SQL Server foreign code from CSV file generated by 99UtilityForeignKey.ps1


CLS
$sourceFilePath = "T:\Documents\kDSResearch2020\foriegnKey20200519.csv"
$sqlFilePathResult  =  "T:\Documents\kDSResearch2020\ForeignKey20200519.sql"
$destinationServerName = "DATABASESERVERNAMEGOESHERE\MSSQLSERVER2019"
$database = "Covid19DataVault"
$queryString = "EXEC [Utility].[upGenerateDataVaultForeignKey]"


$outerTemplate = @'
BEGIN TRANSACTION

$($items -join "`n")  
COMMIT TRANSACTION
'@


$innerTemplate = @'
ALTER TABLE $($item.Schema).$($item.Table) ADD CONSTRAINT $($item.ConstraintName) 
FOREIGN KEY ($($item.ForeignKeyColumn))
REFERENCES  $($item.ReferenceTableColumn); `n
'@

#generate CSV file
Invoke-Sqlcmd -ServerInstance $destinationServerName -Database $database -QueryTimeout 1000 -Query $queryString | Export-Csv $sourceFilePath -Delimiter "," -NoTypeInformation

$currentFile = $sourceFilePath

Write-Host $currentFile 

#generate foreign key sql

$sql = Import-Csv $currentFile | Group-Object Date -ov grp | ForEach-Object {
$items = foreach ($item in $_.Group) {
$ExecutionContext.InvokeCommand.ExpandString($innerTemplate)
}
$ExecutionContext.InvokeCommand.ExpandString($outerTemplate) 
}

Write-Host $sql
Set-Content -Path ($sqlFilePathResult) -Value $sql

Write-Host "Script Created"